# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\W0433181\Desktop\Programming\Laercio_da_silva-1\TechChecks\TC7\TaxCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelWhatIs = QtWidgets.QLabel(self.centralwidget)
        self.labelWhatIs.setGeometry(QtCore.QRect(20, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelWhatIs.setFont(font)
        self.labelWhatIs.setObjectName("labelWhatIs")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSalary.setGeometry(QtCore.QRect(340, 40, 131, 20))
        self.lineEditSalary.setObjectName("lineEditSalary")
        self.lineEditDependents = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDependents.setGeometry(QtCore.QRect(340, 90, 51, 20))
        self.lineEditDependents.setObjectName("lineEditDependents")
        self.pushButtonCalculateTax = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculateTax.setGeometry(QtCore.QRect(150, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalculateTax.setFont(font)
        self.pushButtonCalculateTax.setObjectName("pushButtonCalculateTax")
        self.labelProvincialTax = QtWidgets.QLabel(self.centralwidget)
        self.labelProvincialTax.setGeometry(QtCore.QRect(20, 200, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelProvincialTax.setFont(font)
        self.labelProvincialTax.setText("")
        self.labelProvincialTax.setObjectName("labelProvincialTax")
        self.labelDependentDeduction = QtWidgets.QLabel(self.centralwidget)
        self.labelDependentDeduction.setGeometry(QtCore.QRect(20, 240, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelDependentDeduction.setFont(font)
        self.labelDependentDeduction.setText("")
        self.labelDependentDeduction.setObjectName("labelDependentDeduction")
        self.labelTotalWithheld = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalWithheld.setGeometry(QtCore.QRect(20, 260, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelTotalWithheld.setFont(font)
        self.labelTotalWithheld.setText("")
        self.labelTotalWithheld.setObjectName("labelTotalWithheld")
        self.labelTotalTakeHomePay = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalTakeHomePay.setGeometry(QtCore.QRect(20, 280, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelTotalTakeHomePay.setFont(font)
        self.labelTotalTakeHomePay.setText("")
        self.labelTotalTakeHomePay.setObjectName("labelTotalTakeHomePay")
        self.labelFederalTax = QtWidgets.QLabel(self.centralwidget)
        self.labelFederalTax.setGeometry(QtCore.QRect(20, 220, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelFederalTax.setFont(font)
        self.labelFederalTax.setText("")
        self.labelFederalTax.setObjectName("labelFederalTax")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tax Calculator"))
        self.labelWhatIs.setText(_translate("MainWindow", "What is your weekly salary?"))
        self.label_2.setText(_translate("MainWindow", "How many dependents do you have?"))
        self.pushButtonCalculateTax.setText(_translate("MainWindow", "Calculate Tax"))
